apiVersion: v1
kind: Service
metadata:
  name: {{ include "devsecops.backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devsecops.labels" . | nindent 4 }}
    app.kubernetes.io/name: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: http
      protocol: TCP
