apiVersion: v1
kind: Service
metadata:
  name: {{ include "devsecops.db.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devsecops.labels" . | nindent 4 }}
    app.kubernetes.io/name: db
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: db
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
