apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devsecops.secret.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devsecops.labels" . | nindent 4 }}
type: Opaque
data:
  # Values are base64-encoded at template render time by Helm.
  db-username: {{ .Values.db.auth.username | b64enc | quote }}
  db-password: {{ .Values.db.auth.password | b64enc | quote }}
  db-name:     {{ .Values.db.auth.database | b64enc | quote }}
