apiVersion: v1
kind: Service
metadata:
  name: {{ include "dso.backend.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "dso-helm.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "dso.backend.name" . }}
    app.kubernetes.io/part-of: {{ include "dso-helm.name" . }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "dso.backend.name" . }}
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      protocol: TCP
