apiVersion: v1
kind: Service
metadata:
  name: {{ include "dso.db.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "dso-helm.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "dso.db.name" . }}
    app.kubernetes.io/part-of: {{ include "dso-helm.name" . }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "dso.db.name" . }}
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
