apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dso.pvc.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "dso-helm.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: {{ include "dso-helm.name" . }}
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
